# Generated by Django 3.2.3 on 2021-06-03 11:31

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64, verbose_name='First Name')),
                ('lname', models.CharField(max_length=64, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('image', models.ImageField(default='teacher_pic/default.jpg', upload_to=teachers.models.image_path)),
            ],
        ),
    ]
