# Generated by Django 3.2.3 on 2021-06-03 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20210603_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 17, 23, 41, 829153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher', to='teachers.Subject'),
        ),
    ]
