# Generated by Django 3.2.3 on 2021-06-03 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210603_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 17, 23, 56, 192639, tzinfo=utc)),
        ),
    ]
