# Generated by Django 3.2.3 on 2021-06-07 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_auto_20210607_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercomment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 4, 58, 45, 184702, tzinfo=utc)),
        ),
    ]
